version: "3"

services:

 eri-ent-app:
  image: medhanie/eri-ent-app
  networks:
   - eri-ent-network
  ports:
   - 80:8080
  depends_on:
    - database

 database:
  image: mysql
  networks:
   - eri-ent-network
  environment:
   - MYSQL_ROOT_PASSWORD=changeitpls
   - MYSQL_DATABASE=erient

networks:
 eri-ent-network: