version: "3"

services:

 eri-ent-app:
  image: medhanie/eri-ent-app
  networks:
   - eri-ent-network
  ports:
   - 8080:8080
  depends_on:
    - database

 database:
  image: mysql
  networks:
   - eri-ent-network
  ports:
    - 3306
  environment:
   - MYSQL_ROOT_PASSWORD=changeitpls
   - MYSQL_DATABASE=erient
 #  ERIENT_DB_LOCATION = /Users/medhanie/db/mysql
  volumes:
    - /Users/medhanie/db/mysql:/var/lib/mysql

networks:
 eri-ent-network: